# Generated by Django 3.0.5 on 2020-10-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=250, null=True)),
                ('room_availability', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('hotel_address', models.CharField(blank=True, max_length=250, null=True)),
                ('hotel_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('hotel_detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
