# Generated by Django 3.0.5 on 2020-10-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='HotelDetail',
        ),
    ]
